### ISSUE TITLE
previous state has no effect on state

### ISSUE THREAD

**Issue by ypxie** [andreamad8/Universal-Transformer-Pytorch#1]
previous_state = ((state * update_weights.unsqueeze(-1)) + (previous_state * (1 - update_weights.unsqueeze(-1))))

**Comment by ypxie** [comment]
it looks like previous_state is not being used at all

**Comment by andreamad8** [comment]
Hi, 

I think you are right. The function should return previous_state instead of state. 

I converted this implementation from: https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/research/universal_transformer_util.py#L1062 

where they use tf.while() is quite difficult to follow. I think if I return previous_state (the equivalent of new_state in the tf code) instead of state, should work. 

I will push a fix. Let me know if do you think is correct. Any help is greatly appreciated.

Andrea

**Comment by andreamad8** [comment]
Ok, I also run some test, and now works way better. Really thanks. 

This weekend I will run more experiments on babi. I think I will also include original transformer.

**Comment by ypxie** [comment]
Glad to know that and thanks for open-sourcing it! : )

**Comment by andreamad8** [comment]
No problem, let me know if you spot any other bug. 👍
